### ISSUE TITLE
Search Feature Request

### ISSUE THREAD

**Issue by Lehrules** [TheWicklowWolf/eBookBuddy#2]
I love this interface and it's simplicity. Is there any way we could have a search function? I would love to use this as my primary way to add books to Readarr.

**Comment by TheWicklowWolf** [comment]
I tried to avoid overlapping functions, and since Readarr already has a search feature, I didn't implement one.

I'll keep this in mind for future updates, and I am open to PRs too.

**Comment by MoSattler** [comment]
Would also love that! Readarr is less nice for non technical user, while ebookbuddy is a bit more intuitiv!

**Comment by TheWicklowWolf** [comment]
@MoSattler The Readarr search works OK, it's just a bit slow. 

And it's still getting back on track after experiencing issues with its metadata provider: 
https://wiki.servarr.com/readarr/status

**Comment by MoSattler** [comment]
I am sure it works just fine, but it doesnt work well for my use because of it's UX. It's not straightforward to use for non-technical people. It's also easy to mess up and do things they didnt intend to in Readarr. So I'd rather not give non-technical people access to it.

I'd rather have a simply UI where one can get simple recommendations and a search bar, and that's it. I was thinking about coding something like this myself, but it seems like Goodreads isn't giving out any more API keys.

**Comment by TheWicklowWolf** [comment]
> but it seems like Goodreads isn't giving out any more API keys.

Thats the main issue.

As I said I'm open to PRs, if you feel like integrating it here.
